# fuzzel 启动器配置。
[main]
font=Noto Sans, Noto Sans CJK SC:size=13
dpi-aware=no
icons-enabled=yes

[colors]
background=1a1b26ee
text=c0caf5ff
match=7fc8ffff
selection=33415eff
selection-text=c0caf5ff
border=7fc8ffff

[border]
width=1
radius=8
